INSERT INTO rental_products (
  id,
  brand_slugs,
  category_slug,
  slug,
  name,
  short_description,
  full_description,
  image_src,
  gallery_images,
  price,
  quantity_available,
  delivery_fee,
  is_active,
  required_space,
  dimensions,
  item_rules,
  allowed_surfaces,
  inventory_tracked
) VALUES

-- ─── JUMPERS ──────────────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'jumpers', 'regular-jumper-13x13',
 'Regular Jumper 13×13',
 'The classic backyard bounce house — bright, clean, and ready for any party.',
 'A 13×13 standard jumper perfect for ages 3–12. Includes full safety mesh, front step, and dual anchor points. Fits most side yards and backyards.',
 '/products/jumpers/regular-jumper-13x13/main.jpg',
 '["/products/jumpers/regular-jumper-13x13/1.jpg","/products/jumpers/regular-jumper-13x13/2.jpg"]'::jsonb,
 125, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'jumpers', 'regular-jumper-15x15',
 'Regular Jumper 15×15',
 'More room to bounce — the go-to upgrade for bigger groups and older kids.',
 'A 15×15 jumper that handles larger crowds with ease. Full mesh panels, bright artwork, and the same pro delivery and setup as every unit we run.',
 '/products/jumpers/regular-jumper-15x15/main.jpg',
 '["/products/jumpers/regular-jumper-15x15/1.jpg","/products/jumpers/regular-jumper-15x15/2.jpg"]'::jsonb,
 125, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'jumpers', 'sports-jumper',
 'Sports Jumper',
 'Soccer, basketball, and football graphics — the MVP pick for team parties.',
 'Sport-themed artwork that photographs great at tailgates, team celebrations, and school fairs. Same 13×13 footprint as our classic jumper.',
 '/products/jumpers/sports-jumper/main.jpg',
 '["/products/jumpers/sports-jumper/1.jpg","/products/jumpers/sports-jumper/2.jpg"]'::jsonb,
 125, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'jumpers', 'princess-castle-jumper',
 'Princess Castle Jumper',
 'Tall turrets, pastel colors — every little royal deserves this one.',
 'A castle-style jumper with four turrets, pink and purple tones, and princess artwork on every panel. A crowd favorite at birthday parties across Moreno Valley.',
 '/products/jumpers/princess-castle-jumper/main.jpg',
 '["/products/jumpers/princess-castle-jumper/1.jpg","/products/jumpers/princess-castle-jumper/2.jpg"]'::jsonb,
 125, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'jumpers', 'toddler-jumper',
 'Toddler Jumper',
 'Built for the littlest guests — smaller entry, softer design, maximum fun.',
 'A scaled-down jumper designed specifically for kids under 5. Lower entry height, wide interior, and soft color scheme. Safe, cute, and the first thing parents notice.',
 '/products/jumpers/toddler-jumper/main.jpg',
 '["/products/jumpers/toddler-jumper/1.jpg","/products/jumpers/toddler-jumper/2.jpg"]'::jsonb,
 250, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── DISNEY JUMPERS ───────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'disney-jumpers', 'mickey-mouse-jumper',
 'Mickey Mouse Jumper',
 'The mouse that started it all — instantly recognized, wildly requested.',
 'Official Mickey Mouse themed artwork on every panel. Kids lose their minds when they see it inflate. Perfect for Disney-themed birthdays and character parties.',
 '/products/disney-jumpers/mickey-mouse-jumper/main.jpg',
 '["/products/disney-jumpers/mickey-mouse-jumper/1.jpg","/products/disney-jumpers/mickey-mouse-jumper/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'disney-jumpers', 'minnie-mouse-jumper',
 'Minnie Mouse Jumper',
 'Pink, polka dots, and Minnie — the birthday girl will not stop smiling.',
 'Bright Minnie Mouse themed jumper with signature pink and white polka dot panels. A top pick for toddler and kids birthday parties in Moreno Valley.',
 '/products/disney-jumpers/minnie-mouse-jumper/main.jpg',
 '["/products/disney-jumpers/minnie-mouse-jumper/1.jpg","/products/disney-jumpers/minnie-mouse-jumper/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'disney-jumpers', 'frozen-elsa-jumper',
 'Frozen Elsa Jumper',
 'Let it go — right into this icy blue Elsa jumper they will love.',
 'Frozen-themed jumper in cool blues and purples featuring Elsa and Anna artwork. The most-requested character theme for girls birthday parties.',
 '/products/disney-jumpers/frozen-elsa-jumper/main.jpg',
 '["/products/disney-jumpers/frozen-elsa-jumper/1.jpg","/products/disney-jumpers/frozen-elsa-jumper/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'disney-jumpers', 'spiderman-jumper',
 'Spider-Man Jumper',
 'With great power comes the best birthday ever — Spidey approved.',
 'Spider-Man themed jumper with red, blue, and web graphics on all panels. Always a hit for superhero parties. Works for boys and girls who love the web-slinger.',
 '/products/disney-jumpers/spiderman-jumper/main.jpg',
 '["/products/disney-jumpers/spiderman-jumper/1.jpg","/products/disney-jumpers/spiderman-jumper/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'disney-jumpers', 'paw-patrol-jumper',
 'PAW Patrol Jumper',
 'Chase is on the case — and so is every kid at this party.',
 'PAW Patrol themed jumper featuring Chase, Marshall, and the whole crew. One of the most-booked character units for kids under 7. Looks incredible in photos.',
 '/products/disney-jumpers/paw-patrol-jumper/main.jpg',
 '["/products/disney-jumpers/paw-patrol-jumper/1.jpg","/products/disney-jumpers/paw-patrol-jumper/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── FIVE-IN-ONE JUMPERS ──────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'five-in-one-jumpers', 'five-in-one-standard',
 '5-in-1 Combo Standard',
 'Five activities in one unit — bounce, slide, climb, crawl, and basketball.',
 'The ultimate all-in-one: jump area, slide, climbing wall, crawl-through tunnel, and basketball hoop. Fits bigger gatherings when one activity is never enough.',
 '/products/five-in-one-jumpers/five-in-one-standard/main.jpg',
 '["/products/five-in-one-jumpers/five-in-one-standard/1.jpg","/products/five-in-one-jumpers/five-in-one-standard/2.jpg"]'::jsonb,
 280, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'five-in-one-jumpers', 'five-in-one-princess',
 '5-in-1 Princess Combo',
 'All five activities wrapped in a princess theme — she gets the works.',
 'Same five-activity layout as our standard combo but dressed in pink, purple, and gold princess artwork. Perfect when the birthday girl wants more than just a bounce.',
 '/products/five-in-one-jumpers/five-in-one-princess/main.jpg',
 '["/products/five-in-one-jumpers/five-in-one-princess/1.jpg","/products/five-in-one-jumpers/five-in-one-princess/2.jpg"]'::jsonb,
 280, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── COMBOS ───────────────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'combos', 'princess-3d-combo',
 'Princess 3D Combo',
 '3D character cutouts and a slide — the most photogenic unit in our fleet.',
 'A bounce-and-slide combo featuring raised 3D princess sculptures on the exterior panels. The setup that makes parents stop and pull out their phones the moment it inflates.',
 '/products/combos/princess-3d-combo/main.jpg',
 '["/products/combos/princess-3d-combo/1.jpg","/products/combos/princess-3d-combo/2.jpg"]'::jsonb,
 275, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'combos', 'superhero-combo',
 'Superhero Combo',
 'Bounce area plus slide — perfect for the kid who wants to save the world.',
 'Superhero-themed combo jumper with attached slide. Features Marvel-inspired graphics and a roomy bounce area that handles mixed-age groups without crowding.',
 '/products/combos/superhero-combo/main.jpg',
 '["/products/combos/superhero-combo/1.jpg","/products/combos/superhero-combo/2.jpg"]'::jsonb,
 250, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'combos', 'tropical-combo',
 'Tropical Combo',
 'Bounce plus dry slide with lush tropical colors — instant backyard resort.',
 'A combo unit with a generous jump area and attached slide in bright tropical palm graphics. Great for summer parties, school fairs, and company picnics.',
 '/products/combos/tropical-combo/main.jpg',
 '["/products/combos/tropical-combo/1.jpg","/products/combos/tropical-combo/2.jpg"]'::jsonb,
 250, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'combos', 'jungle-combo',
 'Jungle Combo',
 'Wild animals, big slide, bigger energy — adventure starts at delivery.',
 'Jungle-themed combo featuring lions, giraffes, and elephants on the exterior. Attached slide adds a second activity that keeps lines moving and kids smiling.',
 '/products/combos/jungle-combo/main.jpg',
 '["/products/combos/jungle-combo/1.jpg","/products/combos/jungle-combo/2.jpg"]'::jsonb,
 250, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── MINI COMBOS ──────────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'mini-combo', 'mini-combo-princess',
 'Mini Princess Combo',
 'All the magic of a combo in a smaller footprint — made for tighter spaces.',
 'A compact bounce-and-slide combo in princess pink and purple. Fits yards where a full-size combo will not. Great for toddler parties and small backyard setups.',
 '/products/mini-combo/mini-combo-princess/main.jpg',
 '["/products/mini-combo/mini-combo-princess/1.jpg","/products/mini-combo/mini-combo-princess/2.jpg"]'::jsonb,
 200, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'mini-combo', 'mini-combo-sport',
 'Mini Sport Combo',
 'Compact sports combo — big fun, small footprint, easy on the budget.',
 'Mini combo with sport-themed graphics and an attached slide. At a smaller footprint than our full combos, it fits tight side yards while still delivering the wow factor.',
 '/products/mini-combo/mini-combo-sport/main.jpg',
 '["/products/mini-combo/mini-combo-sport/1.jpg","/products/mini-combo/mini-combo-sport/2.jpg"]'::jsonb,
 200, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── SLIDES DRY / WET ─────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'slides-dry-wet', 'waterslide-palm-breeze-16ft',
 'Palm Breeze 16ft Waterslide',
 'Cool off in style — 16 feet of slide with a built-in splash pool.',
 'A 16-foot waterslide with tropical palm graphics and an attached splash landing pool. Includes water connection kit. Best summer upgrade for any backyard party.',
 '/products/slides-dry-wet/waterslide-palm-breeze-16ft/main.jpg',
 '["/products/slides-dry-wet/waterslide-palm-breeze-16ft/1.jpg","/products/slides-dry-wet/waterslide-palm-breeze-16ft/2.jpg"]'::jsonb,
 280, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'slides-dry-wet', 'waterslide-dual-lane-20ft',
 'Dual Lane Waterslide 20ft',
 'Race your friends down 20 feet of slide — two lanes, zero waiting.',
 'Twin-lane waterslide at 20 feet tall with side-by-side racing lanes and a wide splash pool at the bottom. The most popular water rental for summer graduation parties.',
 '/products/slides-dry-wet/waterslide-dual-lane-20ft/main.jpg',
 '["/products/slides-dry-wet/waterslide-dual-lane-20ft/1.jpg","/products/slides-dry-wet/waterslide-dual-lane-20ft/2.jpg"]'::jsonb,
 300, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'slides-dry-wet', 'waterslide-canyon-plunge-20ft',
 'Canyon Plunge 20ft Waterslide',
 'The tallest, fastest water rental in our lineup — not for the timid.',
 'A 20-foot single-lane waterslide with steep pitch and canyon rock graphics. Long run-out splash pool. Requires a level area and good water pressure. A crowd stopper.',
 '/products/slides-dry-wet/waterslide-canyon-plunge-20ft/main.jpg',
 '["/products/slides-dry-wet/waterslide-canyon-plunge-20ft/1.jpg","/products/slides-dry-wet/waterslide-canyon-plunge-20ft/2.jpg"]'::jsonb,
 300, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'slides-dry-wet', 'dry-slide-dual-lane',
 'Dual Lane Dry Slide',
 'All the racing excitement of water slides — no swimsuits required.',
 'Side-by-side racing dry slide for year-round use. At 18 feet, it delivers serious speed without water. Great for fall events, school fairs, and venues where water is not an option.',
 '/products/slides-dry-wet/dry-slide-dual-lane/main.jpg',
 '["/products/slides-dry-wet/dry-slide-dual-lane/1.jpg","/products/slides-dry-wet/dry-slide-dual-lane/2.jpg"]'::jsonb,
 280, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── OBSTACLE COURSES ─────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'obstacle-course', 'obstacle-course-jungle',
 'Jungle Obstacle Course',
 'Crawl, climb, and slide through the jungle — the ultimate team challenge.',
 'A 40-foot obstacle course with crawl tunnels, pop-up obstacles, climbing walls, and a final slide. Jungle-themed graphics. Perfect for competitive groups and team-building events.',
 '/products/obstacle-course/obstacle-course-jungle/main.jpg',
 '["/products/obstacle-course/obstacle-course-jungle/1.jpg","/products/obstacle-course/obstacle-course-jungle/2.jpg"]'::jsonb,
 280, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'obstacle-course', 'obstacle-course-sports',
 'Sports Obstacle Course',
 'From pop-ups to the finish line — the party does not stop moving.',
 'Sports-themed 40-foot obstacle course designed for ages 5 and up. Features balance beams, climb walls, squeeze tunnels, and a victory slide at the end. Big group crowd-pleaser.',
 '/products/obstacle-course/obstacle-course-sports/main.jpg',
 '["/products/obstacle-course/obstacle-course-sports/1.jpg","/products/obstacle-course/obstacle-course-sports/2.jpg"]'::jsonb,
 280, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── INFLATABLE GAMES ─────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'inflatable-games', 'boxing-ring-inflatable',
 'Inflatable Boxing Ring',
 'Giant gloves, safe padding, instant crowd — adults get competitive fast.',
 'Inflatable boxing ring with oversized padded gloves included. Safe for all ages, endlessly entertaining for adults. The one rental that always draws a crowd of spectators.',
 '/products/inflatable-games/boxing-ring-inflatable/main.jpg',
 '["/products/inflatable-games/boxing-ring-inflatable/1.jpg","/products/inflatable-games/boxing-ring-inflatable/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'inflatable-games', 'bungee-run',
 'Bungee Run',
 'Sprint, stretch, and snap back — the most laughed-at game we own.',
 'Two-lane bungee run where players race to place a marker as far as possible before the bungee pulls them back. Equally hilarious for kids and adults.',
 '/products/inflatable-games/bungee-run/main.jpg',
 '["/products/inflatable-games/bungee-run/1.jpg","/products/inflatable-games/bungee-run/2.jpg"]'::jsonb,
 175, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'inflatable-games', 'jousting-arena',
 'Jousting Arena',
 'Padded jousting on a raised beam — friendly battles, unforgettable photos.',
 'Inflatable jousting platform with two padded pedestals and foam jousting poles. Safe, competitive, and produces the funniest action shots of any game we carry.',
 '/products/inflatable-games/jousting-arena/main.jpg',
 '["/products/inflatable-games/jousting-arena/1.jpg","/products/inflatable-games/jousting-arena/2.jpg"]'::jsonb,
 175, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── TABLES & CHAIRS ──────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'tables-chairs', 'tables-chairs-small-package',
 'Tables & Chairs — Small Package',
 '5 tables and 40 chairs delivered, set up, and picked up — done.',
 'Includes five 60-inch round folding tables and forty white folding chairs. Perfect for gatherings of 30–50 guests. We deliver, set up, and break down — you just host.',
 '/products/tables-chairs/tables-chairs-small-package/main.jpg',
 '["/products/tables-chairs/tables-chairs-small-package/1.jpg","/products/tables-chairs/tables-chairs-small-package/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'tables-chairs', 'tables-chairs-large-package',
 'Tables & Chairs — Large Package',
 '10 tables and 80 chairs — everything you need to seat the whole crowd.',
 'Ten 60-inch round tables and eighty white folding chairs. Handles events of 60–100 guests comfortably. Add a canopy for a complete outdoor dining setup.',
 '/products/tables-chairs/tables-chairs-large-package/main.jpg',
 '["/products/tables-chairs/tables-chairs-large-package/1.jpg","/products/tables-chairs/tables-chairs-large-package/2.jpg"]'::jsonb,
 250, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── CANOPIES & TENTS ─────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'canopies-tent', 'canopy-10x10',
 '10×10 Canopy',
 'Clean white shade for any setup — light, fast, and always on time.',
 'A 10×10 white pop-up canopy with weighted base. Ideal for DJ booths, food stations, gift tables, or extra shade. Easy to pair with any of our jumper or table packages.',
 '/products/canopies-tent/canopy-10x10/main.jpg',
 '["/products/canopies-tent/canopy-10x10/1.jpg","/products/canopies-tent/canopy-10x10/2.jpg"]'::jsonb,
 75, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'canopies-tent', 'party-tent-20x20',
 '20×20 Party Tent',
 'Shade the whole crowd — a 20×20 tent changes the entire vibe of your setup.',
 'A 20×20 frame tent in white. Covers up to 40 guests for dining, protects your setup from sun, and anchors the visual center of any backyard event. Setup included.',
 '/products/canopies-tent/party-tent-20x20/main.jpg',
 '["/products/canopies-tent/party-tent-20x20/1.jpg","/products/canopies-tent/party-tent-20x20/2.jpg"]'::jsonb,
 200, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── THRONE CHAIRS ────────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'throne-chairs', 'king-throne-chair',
 'King Throne Chair',
 'One chair, infinite presence — make the guest of honor feel like royalty.',
 'A tall, ornate throne chair in white and gold finish. Perfect for the birthday honoree, quinceañera, or head of the table. Makes every photo look like an event.',
 '/products/throne-chairs/king-throne-chair/main.jpg',
 '["/products/throne-chairs/king-throne-chair/1.jpg","/products/throne-chairs/king-throne-chair/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'throne-chairs', 'queen-throne-chair',
 'Queen Throne Chair',
 'Her day, her throne — a statement piece every guest will photograph.',
 'Elegant queen throne in white with rose gold accents. Slightly lower profile than the king chair, perfectly proportioned for a seated portrait setup. Pairs beautifully with our king chair.',
 '/products/throne-chairs/queen-throne-chair/main.jpg',
 '["/products/throne-chairs/queen-throne-chair/1.jpg","/products/throne-chairs/queen-throne-chair/2.jpg"]'::jsonb,
 150, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

(gen_random_uuid(), ARRAY['lias','crb'], 'throne-chairs', 'his-and-hers-throne-set',
 'His & Hers Throne Set',
 'Two thrones, one perfect photo — the matching set that elevates any event.',
 'King and queen throne chairs delivered together as a matched set in white and gold. Ideal for gender reveals, baby showers, quinceañeras, and couple birthday celebrations.',
 '/products/throne-chairs/his-and-hers-throne-set/main.jpg',
 '["/products/throne-chairs/his-and-hers-throne-set/1.jpg","/products/throne-chairs/his-and-hers-throne-set/2.jpg"]'::jsonb,
 275, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true),

-- ─── XTREME DISCO DOME ────────────────────────────────────────────────────────
(gen_random_uuid(), ARRAY['lias','crb'], 'xtreme-disco-dome', 'xtreme-disco-dome',
 'Xtreme Disco Dome',
 'Lights, music, bounce — the most talked-about rental in the Inland Empire.',
 'An inflatable dome with built-in LED disco lighting and mirror ball effect inside. Kids and adults bounce together in a full sensory experience. Unlike anything else we carry.',
 '/products/xtreme-disco-dome/xtreme-disco-dome/main.jpg',
 '["/products/xtreme-disco-dome/xtreme-disco-dome/1.jpg","/products/xtreme-disco-dome/xtreme-disco-dome/2.jpg"]'::jsonb,
 300, 1, 0, true, NULL, NULL, NULL, ARRAY['Grass','Concrete'], true);
